package com.nmbb.oplayer.ui.search;

/**
 * Created with IntelliJ IDEA.
 * User: Maxim
 * Date: 1/29/13
 * Time: 9:16 AM
 * To change this template use File | Settings | File Templates.
 */
public class SearchKeywordsConverter {
    //                           %C0-%E0-%C1-%E1-%C2-%E2-%C3-%E3-%C4-%E4-%C5-%E5-%A8-%B8-%C6-%E6-%C7-%E7-%C8-%E8-%C9-%E9-%CA-%EA-%CB-%EB-%CC-%EC-%CD-%ED-%CE-%EE-%CF-%EF-%D0-%F0-%D1-%F1-%D2-%F2-%D3-%F3-%D4-%F4-%D5-%F5-%D6-%F6-%D7-%F7-%DB-%FB-%DC-%FC-%DD-%FD-%DE-%FE-%DF-%FF-+-%60-%7E-%21-%23-%B9-$-%3B-%-%5E-%3A-%26-%3F-*-%28-%29-%3D-%2F-%5C-,-%7C%24
    static String[] coddedChars = new String[]{
            "%20",   //" "
            "%D0%B0", //"а",
            "%D0%B1", //"б",
            "%D0%B2", //"в",
            "%D0%B3", //"г",
            "%D0%B4", //"д",
            "%D0%B5", //"е",
            "%D1%91", //"ё",
            "%D0%B6", //"ж",
            "%D0%B7", //"з",
            "%D0%B8", //"и",
            "%D0%B9", //"й",
            "%D0%BA", //"к",
            "%D0%BB", //"л",
            "%D0%BC", //"м",
            "%D0%BD", //"н",
            "%D0%BE", //"о",
            "%D0%BF", //"п",
            "%D1%80", //"р",
            "%D1%81", //"с",
            "%D1%82", //"т",
            "%D1%83", //"у",
            "%D1%84", //"ф",
            "%D1%85", //"х",
            "%D1%86", //"ц",
            "%D1%87", //"ч",
            "%D1%88", //"ш",
            "%D1%89", //"щ",
            "%D1%8A", //"ъ",
            "%D1%8B", //"ы",
            "%D1%8C", //"ь",
            "%D1%8D", //"э",
            "%D1%8E", //"ю",
            "%D1%8F", //"я"

    };
    static String[] encodedChars = new String[]{
            " ",
            "а",
            "б",
            "в",
            "г",
            "д",
            "е",
            "ё",
            "ж",
            "з",
            "и",
            "й",
            "к",
            "л",
            "м",
            "н",
            "о",
            "п",
            "р",
            "с",
            "т",
            "у",
            "ф",
            "х",
            "ц",
            "ч",
            "ш",
            "щ",
            "ъ",
            "ы",
            "ь",
            "э",
            "ю",
            "я"
    };
    //%D1%80%D0%B5
static String[] coddedCharsForLinks = new String[]{
            "%C0",
            "%E0",
            "%C1",
            "%E1",
            "%C2",
            "%E2",
            "%C3",
            "%E3",
            "%C4",
            "%E4",
            "%C5",
            "%E5",
            "%A8",
            "%B8",
            "%C6",
            "%E6",
            "%C7",
            "%E7",
            "%C8",
            "%E8",
            "%C9",
            "%E9",
            "%CA",
            "%EA",
            "%CB",
            "%EB",
            "%CC",
            "%EC",
            "%CD",
            "%ED",
            "%CE",
            "%EE",
            "%CF",
            "%EF",
            "%D0",
            "%F0",
            "%D1", //37
            "%F1",
            "%D2",
            "%F2",
            "%D3",
            "%F3",
            "%D4",
            "%F4",
            "%D5",
            "%F5",
            "%D6",
            "%F6",
            "%D7",
            "%F7",
            "%D8",
            "%F8",
            "%D9",
            "%F9",
            "%DA",
            "%FA",
            "%DB",
            "%FB",
            "%DC",
            "%FC",
            "%DD",
            "%FD",
            "%DE",
            "%FE",
            "%DF",
            "%FF",
            "+",
            "%60",
            "%7E",
            "%21",
            "%23",
            "%B9",
            "%24",
            "%3B",
            "%25",
            "%5E",
//            "%3A",
//            "%26",
//            "%3F",
//            "*",
            "%28",
            "%29",
//            "%3D",
//            "%2F",
            "%5C",
            "%2C",
            "%7C"
    };
    static String[] encodedCharsForLinks = new String[]{
            "А",
            "а",
            "Б",
            "б",
            "В",
            "в",
            "Г",
            "г",
            "Д",
            "д",
            "Е",
            "е",
            "Ё",
            "ё",
            "Ж",
            "ж",
            "З",
            "з",
            "И",
            "и",
            "Й",
            "й",
            "К",
            "к",
            "Л",
            "л",
            "М",
            "м",
            "Н",
            "н",
            "О",
            "о",
            "П",
            "п",
            "Р",
            "р",
            "С",
            "с",
            "Т",
            "т",
            "У",
            "у",
            "Ф",
            "ф",
            "Х",
            "х",
            "Ц",
            "ц",
            "Ч",
            "ч",
            "Ш",
            "ш",
            "Щ",
            "щ",
            "Ъ",
            "ъ",
            "Ы",
            "ы",
            "Ь",
            "ь",
            "Э",
            "э",
            "Ю",
            "ю",
            "Я",
            "я",
            " ",
            "`",
            "~",
            "!",
            "#",
            "№",
            "\\$",
            ";",
            "%",
            "\\^",
//            ":",
//            "\\&",
//            "\\?",
//            "\\*",
            "\\(",
            "\\)",
//            "=",
//            "\\/",
            "\\\\",
            ",",
            "\\|"
    };
    //%D1%80%D0%B5

    public static String getConvertedKeyword(String keyword){
        String encoded;
        String codded;
        for(int i = 0; i < encodedChars.length; i++){
            encoded = encodedChars[i];
            codded = coddedChars[i];
            keyword = keyword.replaceAll(encoded, codded);
        }

        return keyword;
//        return keyword.replace("%25", "%");
    }

    public static String getConvertedKeywordForLinks(String keyword){
        String encoded;
        String codded;
        for(int i = 0; i < encodedCharsForLinks.length; i++){
            encoded = encodedCharsForLinks[i];
            codded = coddedCharsForLinks[i];
            keyword = keyword.replaceAll(encoded, codded);
        }

        return keyword.replace("%25", "%");
    }
}
